# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Michał Krassowski
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupyterlab-rainbow-brackets
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension adding rainbow brackets/parentheses
    to the editor.
python_name: jupyterlab_rainbow_brackets
repository: https://github.com/krassowski/jupyterlab-rainbow-brackets
test: true
viewer_name: ''

